controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_find_all:
    path:       /api/user/find_all
    controller: App\Controller\UsersController::findAll
    methods:    GET

user_create:
    path:       /api/user/create
    controller: App\Controller\UsersController::create
    methods:    POST