controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test:
    path:       /api/test
    controller: App\Controller\UsersController::test
    methods:    GET