controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test:
    path:       /api/create
    controller: App\Controller\UsersController::create
    methods:    POST