controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


########## USUARIOS ##########

user_list:
    path:       /api/user/list
    controller: App\Controller\UsersController::list
    methods:    GET

user_create:
    path:       /api/user/create
    controller: App\Controller\UsersController::create
    methods:    POST

user_update:
    path:       /api/user/update/{id}
    controller: App\Controller\UsersController::update
    methods:    POST

user_delete:
    path:       /api/user/delete/{id}/{soft}
    controller: App\Controller\UsersController::delete
    defaults:
        soft: 0
    methods:    DELETE